name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy Source
        run: cp -r ./lua/rocketnotes ./src/

      - name: List src directory contents
        run: ls -R ./src/

      - name: Lua Busted
        uses: lunarmodules/busted@v2.2.0
