name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq luarocks

      - name: Verify jq installation
        run: jq --version

      - name: Install Busted
        run: luarocks install busted --local

      - name: Create src directory and copy source files
        run: |
          mkdir -p src
          cp -r lua src/
          cp -r tests src/

      - name: List src directory contents
        run: ls -R ./src/

      - name: Run tests with Lua Busted
        run: ~/.luarocks/bin/busted ./src
